# Export slices containing metastases

This notebook goes through each step to export images of the metastases based on the segmentation

In [2]:
# import libraries

import os
import nibabel as nib
import numpy as np
import matplotlib.pyplot as plt
from skimage.measure import label, regionprops
from pathlib import Path
from tqdm import tqdm
import pandas as pd

import imageio as iio
from PIL import Image

In [3]:
def save_slice_as_image(slice_data, output_path):
    # print(slice_data.shape)
    # print(np.mean(slice_data))
    # cv2.imwrite(output_path, slice_data)
    # plt.imsave(output_path, slice_data, cmap='gray')
    # plt.close()
    data = (slice_data * 255).astype(np.uint8)
    image = Image.fromarray(data)
    image.save(output_path)

# turn images 90 degress
def turn_image_90(image):
    return np.rot90(image, 3)

# mirror images
def mirror_image(image):
    return np.fliplr(image)

def process_nifty_mask(mask_path, mri_path, output_dir, patient_id=None, mri_sequence=None, save_mask_image = False, save_cut_out = False, area_threshold = 0, dataset = "regensburg"):

    # Load the NIFTI mask file
    img = nib.load(mask_path)
    mask_data = img.get_fdata()

    mri_data = nib.load(mri_path).get_fdata()

    unique_labels = np.unique(mask_data)
    #print(unique_labels)

    match dataset:
        case "regensburg":
            target_label = 1
        case "yale":

            if len(unique_labels) > 3:
                if 1 in unique_labels and 3 in unique_labels:
                    mask_data = np.where(mask_data == 3, 1, mask_data)
                target_label = 1 #3 #1
            else:
                target_label = 3
        case _:
            raise ValueError("Invalid dataset specified.")    

    new_unique_labels = np.unique(mask_data)
    #print(new_unique_labels)

    # Ensure the mask data is 3D
    if mask_data.ndim != 3:
        raise ValueError("The NIFTI mask data is not 3D.")

    # Find all connected components (metastases) with the target label in 3D
    labeled_mask = label(mask_data == target_label, connectivity=3)  # 3D connectivity
    regions = regionprops(labeled_mask)
    
    largest_slices = {}

    # Iterate through each region (metastasis)
    for region in regions:
        # Find the slice with the largest area within this region
        coords = region.coords
        slice_areas = {}
        for coord in coords:
            slice_idx = coord[2]  # Use the correct axis for slice indexing
            if slice_idx not in slice_areas:
                slice_areas[slice_idx] = 0
            slice_areas[slice_idx] += 1

        # Identify the slice index with the largest area for this metastasis
        largest_slice_idx = max(slice_areas, key=slice_areas.get)
        largest_area = slice_areas[largest_slice_idx]

        # Store information about the largest slice for each region
        slice_data = mask_data[:, :, largest_slice_idx]
        largest_slices[region.label] = (largest_area, slice_data, largest_slice_idx, region.label, coords)

    if len(largest_slices) == 0:
        print(f"No metastases found in {mri_path}")
        return
    
    # Save the largest slices as image files
    for label_idx, (area, slice_data, slice_idx, region_label, coords) in largest_slices.items():
        if area > area_threshold:
            full_slice_data = mri_data[:, :, slice_idx]
            mask_slice_data = np.zeros_like(slice_data)

            for coord in coords:
                if coord[2] == slice_idx:
                    mask_slice_data[coord[0], coord[1]] = target_label

            # Create the output path
            output_path = os.path.join(output_dir, f'{patient_id}_metastasis_{slice_idx}_{region_label}_{mri_sequence}.png')            
            save_slice_as_image(mirror_image(turn_image_90(full_slice_data)), output_path)

            if save_mask_image:
                mask_output_path = os.path.join(output_dir, f'{patient_id}_metastasis_{slice_idx}_{region_label}_{mri_sequence}_mask.png')

                # Create a new array with only the pixels of the target label
                mask_slice_data = np.zeros_like(mask_data)
                mask_slice_data[mask_data == target_label] = target_label
                mask_slice_data = mask_slice_data[:, :, slice_idx]

                save_slice_as_image(mirror_image(turn_image_90(mask_slice_data)), mask_output_path)
            

            if save_cut_out:

                for region in regions:
                    single_metastasis_mask = np.zeros_like(mask_data[:, :, slice_idx])
                    for coord in coords:
                        if coord[2] == slice_idx:
                            single_metastasis_mask[coord[0], coord[1]] = target_label
                    
                    masked_mri_slice = full_slice_data * (single_metastasis_mask == target_label)

                    # Create the output path
                    output_path = os.path.join(output_dir, f'{patient_id}_metastasis_{slice_idx}_{region_label}_{mri_sequence}_cutout.png')
                    save_slice_as_image(mirror_image(turn_image_90(masked_mri_slice)), output_path)

            #print(f"Saved largest slice for metastasis (slice {slice_idx}) with area {area} to {output_path}")

# Example usage
#mask_file_path = '/Users/LennartPhilipp/Desktop/testing_data/derivatives/segmented_AURORA_20240424-122816/sub-01009590/metastasis_unbinarized_floats.nii.gz'
#mri_path = "/Users/LennartPhilipp/Desktop/testing_data/derivatives/preprocessed_brainlesion_20240424-110551/sub-01009590/preprocessed/sub-01009590_fla_bet_normalized.nii.gz"
mask_file_path = "/Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/Pretreat-MetsToBrain-Masks/BraTS-MET-00100-000/BraTS-MET-00100-000-seg.nii.gz"
mri_path = "/Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_dataset_normalized/BraTS-MET-00100-000/n4_normalized_BraTS-MET-00100-000-t1c.nii.gz"
output_directory = '/Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices'
#os.makedirs(output_directory, exist_ok=True)
#process_nifty_mask(mask_file_path, mri_path, output_directory, save_mask_image=True, save_cut_out=True)

## create skript to go through all patients

### Regensburg Dataset

old code

In [17]:
# output: create folder for each patient and save the slices there

# input mri folder: path to all preprocessed patients
# go to each patient and get all 4 mri scans
# input segmentation folder: path to all segmented patients
# go to each patient and get metastatis_unbinarized_floats.nii.gz

path_to_output = Path("/Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices")
path_to_mri_patients = Path("/Users/LennartPhilipp/Desktop/testing_data/derivatives/preprocessed_brainlesion_20240424-110551")
path_to_segmentation_patients = Path("/Users/LennartPhilipp/Desktop/testing_data/derivatives/segmented_AURORA_20240424-122816")

segmentation_patients = [patient for patient in os.listdir(path_to_segmentation_patients) if os.path.isdir(os.path.join(path_to_segmentation_patients, patient))]

for patient in tqdm(segmentation_patients):
    # go through each patient
    
    print(f"currently working on {patient}")

    # create new folder for output for patient
    path_to_patient_output = Path(path_to_output) / Path(patient)
    os.makedirs(path_to_patient_output, exist_ok=True)

    # IMPORTANT!!!!!
    # adjust path for final run
    path_to_segmentation = Path(path_to_segmentation_patients) / Path(patient) / "metastasis_unbinarized_floats.nii.gz"

    path_to_mri_images = Path(path_to_mri_patients) / Path(patient) / "preprocessed"
    mri_images = [file for file in os.listdir(path_to_mri_images) if ".nii.gz" in file]

    for mri_image in mri_images:
        # go through each mri image for the patient

        mri_sequence = mri_image.split("_")[1]

        path_to_mri = Path(path_to_mri_images) / Path(mri_image)
        process_nifty_mask(path_to_segmentation, path_to_mri, path_to_patient_output, patient, mri_sequence)
    
    print(f"done with patient {patient}")
    

  0%|          | 0/5 [00:00<?, ?it/s]

currently working on sub-01009590
Saved largest slice for metastasis (slice 56) with area 424.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01009590/sub-01009590_metastasis_56_t2.png
Saved largest slice for metastasis (slice 56) with area 424.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01009590/sub-01009590_metastasis_56_fla.png
Saved largest slice for metastasis (slice 56) with area 424.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01009590/sub-01009590_metastasis_56_t1c.png


 20%|██        | 1/5 [00:00<00:01,  2.29it/s]

Saved largest slice for metastasis (slice 56) with area 424.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01009590/sub-01009590_metastasis_56_t1.png
done with patient sub-01009590
currently working on sub-01006290
Saved largest slice for metastasis (slice 63) with area 41.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01006290/sub-01006290_metastasis_63_t2.png
Saved largest slice for metastasis (slice 65) with area 33.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01006290/sub-01006290_metastasis_65_t2.png
Saved largest slice for metastasis (slice 64) with area 39.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01006290/sub-01006290_metastasis_64_t2.png
Saved largest slice for metastasis (slice 63) with area 41.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01006290/sub-01006290_metastasis_63_t1c.png
Saved largest slice for metastasis (slice 65) wi

 40%|████      | 2/5 [00:01<00:01,  1.71it/s]

Saved largest slice for metastasis (slice 64) with area 39.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01006290/sub-01006290_metastasis_64_t1.png
Saved largest slice for metastasis (slice 63) with area 41.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01006290/sub-01006290_metastasis_63_fla.png
Saved largest slice for metastasis (slice 65) with area 33.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01006290/sub-01006290_metastasis_65_fla.png
Saved largest slice for metastasis (slice 64) with area 39.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01006290/sub-01006290_metastasis_64_fla.png
done with patient sub-01006290
currently working on sub-01005097
Saved largest slice for metastasis (slice 120) with area 66.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01005097/sub-01005097_metastasis_120_t1.png
Saved largest slice for metastasis (slice 120

 60%|██████    | 3/5 [00:01<00:01,  1.87it/s]

Saved largest slice for metastasis (slice 120) with area 66.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01005097/sub-01005097_metastasis_120_fla.png
Saved largest slice for metastasis (slice 120) with area 66.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01005097/sub-01005097_metastasis_120_t2.png
done with patient sub-01005097
currently working on sub-01015961
Saved largest slice for metastasis (slice 60) with area 552.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01015961/sub-01015961_metastasis_60_t2.png
Saved largest slice for metastasis (slice 43) with area 69.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01015961/sub-01015961_metastasis_43_t2.png
Saved largest slice for metastasis (slice 60) with area 552.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01015961/sub-01015961_metastasis_60_t1c.png
Saved largest slice for metastasis (slice 

 80%|████████  | 4/5 [00:02<00:00,  1.84it/s]

Saved largest slice for metastasis (slice 60) with area 552.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01015961/sub-01015961_metastasis_60_fla.png
Saved largest slice for metastasis (slice 43) with area 69.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01015961/sub-01015961_metastasis_43_fla.png
Saved largest slice for metastasis (slice 60) with area 552.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01015961/sub-01015961_metastasis_60_t1.png
Saved largest slice for metastasis (slice 43) with area 69.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01015961/sub-01015961_metastasis_43_t1.png
done with patient sub-01015961
currently working on sub-01005630
Saved largest slice for metastasis (slice 41) with area 93.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01005630/sub-01005630_metastasis_41_t2.png
Saved largest slice for metastasis (slice 33) 

100%|██████████| 5/5 [00:02<00:00,  1.86it/s]

Saved largest slice for metastasis (slice 41) with area 93.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01005630/sub-01005630_metastasis_41_fla.png
Saved largest slice for metastasis (slice 33) with area 43.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01005630/sub-01005630_metastasis_33_fla.png
Saved largest slice for metastasis (slice 41) with area 93.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01005630/sub-01005630_metastasis_41_t1.png
Saved largest slice for metastasis (slice 33) with area 43.0 to /Users/LennartPhilipp/Desktop/testing_data/derivatives/met_slices/sub-01005630/sub-01005630_metastasis_33_t1.png
done with patient sub-01005630


working with actual segmented files

# IMPORTANT
some patients got processed multiple times, what was up with that?!

In [7]:
# output: create folder for each patient and save the slices there

# input mri folder: path to all preprocessed patients
# go to each patient and get all 4 mri scans
# input segmentation folder: path to all segmented patients
# go to each patient and get metastatis_unbinarized_floats.nii.gz

path_to_output = Path("/Users/LennartPhilipp/Desktop/Uni/Prowiss/Datensatz_RGB/regensburg_slices")
path_to_mri_patients = Path("/Users/LennartPhilipp/Desktop/Uni/Prowiss/Datensatz_RGB/preprocessed_n4_brainlesion_percentile_20240612-083743")
path_to_segmentation_patients = Path("/Users/LennartPhilipp/Desktop/Uni/Prowiss/Datensatz_RGB/Segs_Lennart_Export")

path_to_tsv = Path("/Users/LennartPhilipp/Desktop/Uni/Prowiss/Dateien/participants_01_08_24.tsv")

segmentation_patients = [patient for patient in os.listdir(path_to_segmentation_patients) if "labels" in patient]

pats_to_preprocess = pd.read_csv(path_to_tsv, sep="\t")["participant_id"].tolist()

already_processed_patients = [patient for patient in os.listdir(path_to_output) if os.path.isdir(os.path.join(path_to_output, patient))]

counter = 0

for patient in tqdm(segmentation_patients):
    # go through each patient

    # if counter >= 1:
    #     break
    
    # get patient ID
    patientID = patient.split("_")[0]

    # check if patient ID is in list of patients to preprocess
    if patientID not in pats_to_preprocess:
        continue

    if patientID in already_processed_patients:
        print(f"patient {patientID} already processed")
        continue

    print(f"currently working on {patientID}")

    # create new folder for output for patient
    path_to_patient_output = Path(path_to_output) / Path(patientID)
    os.makedirs(path_to_patient_output, exist_ok=True)

    # IMPORTANT!!!!!
    # adjust path for final run
    path_to_segmentation = Path(path_to_segmentation_patients) / Path(patient)

    path_to_mri_images = Path(path_to_mri_patients) / Path(patientID) / "perc_normalized"
    mri_images = [file for file in os.listdir(path_to_mri_images) if ".nii.gz" in file]

    if mri_images == []:
        print("********************************")
        print(f"patient {patientID} not complete")
        continue

    for mri_image in mri_images:
        # go through each mri image for the patient

        mri_sequence = mri_image.split("_")[1]

        path_to_mri = Path(path_to_mri_images) / Path(mri_image)
        process_nifty_mask(path_to_segmentation, path_to_mri, path_to_patient_output, patientID, mri_sequence,
                           save_mask_image = True,
                           save_cut_out = True,
                           area_threshold = 10)
    
    print(f"done with patient {patientID}")

    counter += 1

print(counter)
    

  0%|          | 0/484 [00:00<?, ?it/s]

currently working on sub-01134825


  0%|          | 1/484 [00:01<09:37,  1.20s/it]

done with patient sub-01134825
currently working on sub-01592849


  0%|          | 2/484 [00:02<09:10,  1.14s/it]

done with patient sub-01592849
currently working on sub-01732889


  1%|          | 3/484 [00:03<09:19,  1.16s/it]

done with patient sub-01732889
currently working on sub-02145605


  1%|          | 4/484 [00:04<08:53,  1.11s/it]

done with patient sub-02145605
currently working on sub-02035864


  1%|          | 5/484 [00:05<09:30,  1.19s/it]

done with patient sub-02035864
currently working on sub-01946271


  1%|          | 6/484 [00:09<16:33,  2.08s/it]

done with patient sub-01946271
currently working on sub-02047436


  1%|▏         | 7/484 [00:10<14:27,  1.82s/it]

done with patient sub-02047436
currently working on sub-01921604


  2%|▏         | 8/484 [00:12<12:34,  1.58s/it]

done with patient sub-01921604
currently working on sub-01779701


  2%|▏         | 9/484 [00:13<12:06,  1.53s/it]

done with patient sub-01779701
currently working on sub-90005297


  2%|▏         | 10/484 [00:14<12:05,  1.53s/it]

done with patient sub-90005297
currently working on sub-01924997


  2%|▏         | 11/484 [00:16<11:04,  1.40s/it]

done with patient sub-01924997
currently working on sub-02012594


  2%|▏         | 12/484 [00:17<10:33,  1.34s/it]

done with patient sub-02012594
currently working on sub-02090355


  3%|▎         | 13/484 [00:18<10:04,  1.28s/it]

done with patient sub-02090355
currently working on sub-01321873


  3%|▎         | 14/484 [00:19<09:38,  1.23s/it]

done with patient sub-01321873
currently working on sub-02155605


  3%|▎         | 15/484 [00:20<10:00,  1.28s/it]

done with patient sub-02155605
currently working on sub-01214172


  3%|▎         | 16/484 [00:22<09:30,  1.22s/it]

done with patient sub-01214172
currently working on sub-01840035


  4%|▎         | 17/484 [00:23<09:05,  1.17s/it]

done with patient sub-01840035
currently working on sub-01479403


  4%|▎         | 18/484 [00:24<08:53,  1.15s/it]

done with patient sub-01479403
currently working on sub-02020631


  4%|▍         | 19/484 [00:25<08:37,  1.11s/it]

done with patient sub-02020631
currently working on sub-02184584


  4%|▍         | 20/484 [00:26<08:42,  1.13s/it]

done with patient sub-02184584
currently working on sub-01018613


  4%|▍         | 21/484 [00:27<08:28,  1.10s/it]

done with patient sub-01018613
currently working on sub-01398968


  5%|▍         | 22/484 [00:28<08:46,  1.14s/it]

done with patient sub-01398968
currently working on sub-01966470


  5%|▍         | 23/484 [00:29<08:46,  1.14s/it]

done with patient sub-01966470
currently working on sub-01055292


  5%|▍         | 24/484 [00:31<09:12,  1.20s/it]

done with patient sub-01055292
currently working on sub-02036854


  5%|▌         | 25/484 [00:32<08:51,  1.16s/it]

done with patient sub-02036854
currently working on sub-01812518


  5%|▌         | 26/484 [00:33<08:41,  1.14s/it]

done with patient sub-01812518
currently working on sub-01621161


  6%|▌         | 27/484 [00:34<08:30,  1.12s/it]

done with patient sub-01621161
currently working on sub-01947074


  6%|▌         | 28/484 [00:35<08:17,  1.09s/it]

done with patient sub-01947074
currently working on sub-02145747


  6%|▌         | 29/484 [00:36<08:15,  1.09s/it]

done with patient sub-02145747
currently working on sub-01698789


  6%|▌         | 30/484 [00:37<08:09,  1.08s/it]

done with patient sub-01698789
currently working on sub-02173158


  6%|▋         | 31/484 [00:39<09:11,  1.22s/it]

done with patient sub-02173158
currently working on sub-02046093


  7%|▋         | 32/484 [00:40<10:01,  1.33s/it]

done with patient sub-02046093
currently working on sub-01870024


  7%|▋         | 33/484 [00:42<12:01,  1.60s/it]

done with patient sub-01870024
currently working on sub-01952689


  7%|▋         | 34/484 [00:43<10:43,  1.43s/it]

done with patient sub-01952689
currently working on sub-02038513


  7%|▋         | 35/484 [00:44<10:00,  1.34s/it]

done with patient sub-02038513
currently working on sub-02014685


  7%|▋         | 36/484 [00:46<09:17,  1.24s/it]

done with patient sub-02014685
currently working on sub-02152734


  8%|▊         | 37/484 [00:47<09:26,  1.27s/it]

done with patient sub-02152734
currently working on sub-01056884


  8%|▊         | 38/484 [00:48<09:09,  1.23s/it]

done with patient sub-01056884
currently working on sub-01861511


  8%|▊         | 39/484 [00:49<08:41,  1.17s/it]

done with patient sub-01861511
currently working on sub-01991292


  8%|▊         | 40/484 [00:50<08:13,  1.11s/it]

done with patient sub-01991292
currently working on sub-01505384


  8%|▊         | 41/484 [00:51<08:18,  1.13s/it]

done with patient sub-01505384
currently working on sub-01771120


  9%|▊         | 42/484 [00:52<08:20,  1.13s/it]

done with patient sub-01771120
currently working on sub-01274157


  9%|▉         | 43/484 [00:53<08:14,  1.12s/it]

done with patient sub-01274157
currently working on sub-93003757


  9%|▉         | 44/484 [00:54<07:58,  1.09s/it]

done with patient sub-93003757
currently working on sub-02140670


  9%|▉         | 45/484 [00:56<08:07,  1.11s/it]

done with patient sub-02140670
currently working on sub-02120806


 10%|▉         | 46/484 [00:57<07:56,  1.09s/it]

done with patient sub-02120806
currently working on sub-01764802


 10%|▉         | 47/484 [00:58<07:50,  1.08s/it]

done with patient sub-01764802
currently working on sub-01942928


 10%|▉         | 48/484 [00:59<07:46,  1.07s/it]

done with patient sub-01942928
currently working on sub-01216717


 10%|█         | 49/484 [01:00<07:49,  1.08s/it]

done with patient sub-01216717
currently working on sub-01391984


 10%|█         | 50/484 [01:01<07:43,  1.07s/it]

done with patient sub-01391984
currently working on sub-01494733


 11%|█         | 51/484 [01:02<07:35,  1.05s/it]

done with patient sub-01494733
currently working on sub-01589112


 11%|█         | 52/484 [01:03<08:02,  1.12s/it]

done with patient sub-01589112
currently working on sub-02075769


 11%|█         | 53/484 [01:04<07:56,  1.11s/it]

done with patient sub-02075769
currently working on sub-02088565


 11%|█         | 54/484 [01:05<07:42,  1.08s/it]

done with patient sub-02088565
currently working on sub-01616246


 11%|█▏        | 55/484 [01:06<07:35,  1.06s/it]

done with patient sub-01616246
currently working on sub-01997658


 12%|█▏        | 56/484 [01:07<07:30,  1.05s/it]

done with patient sub-01997658
currently working on sub-01795656


 12%|█▏        | 57/484 [01:08<07:41,  1.08s/it]

done with patient sub-01795656
currently working on sub-01205745


 12%|█▏        | 58/484 [01:10<07:39,  1.08s/it]

done with patient sub-01205745
currently working on sub-01513891


 12%|█▏        | 59/484 [01:11<07:38,  1.08s/it]

done with patient sub-01513891
currently working on sub-01516702


 12%|█▏        | 60/484 [01:12<08:46,  1.24s/it]

done with patient sub-01516702
currently working on sub-01717958


 13%|█▎        | 61/484 [01:13<08:31,  1.21s/it]

done with patient sub-01717958
currently working on sub-01789555


 13%|█▎        | 62/484 [01:15<08:52,  1.26s/it]

done with patient sub-01789555
currently working on sub-01040149


 13%|█▎        | 63/484 [01:16<09:06,  1.30s/it]

done with patient sub-01040149
currently working on sub-01883957


 13%|█▎        | 64/484 [01:18<09:38,  1.38s/it]

done with patient sub-01883957
currently working on sub-01335279


 13%|█▎        | 65/484 [01:19<08:52,  1.27s/it]

done with patient sub-01335279
currently working on sub-01433377


 14%|█▎        | 66/484 [01:20<08:20,  1.20s/it]

done with patient sub-01433377
currently working on sub-01957247


 14%|█▍        | 67/484 [01:21<07:57,  1.15s/it]

done with patient sub-01957247
currently working on sub-02131818


 14%|█▍        | 68/484 [01:22<08:22,  1.21s/it]

done with patient sub-02131818
currently working on sub-01190738


 14%|█▍        | 69/484 [01:24<09:21,  1.35s/it]

done with patient sub-01190738
currently working on sub-02119444


 14%|█▍        | 70/484 [01:25<08:46,  1.27s/it]

done with patient sub-02119444
currently working on sub-90005031


 15%|█▍        | 71/484 [01:26<08:16,  1.20s/it]

done with patient sub-90005031
currently working on sub-01990699


 15%|█▍        | 72/484 [01:27<08:07,  1.18s/it]

done with patient sub-01990699
currently working on sub-02015730


 15%|█▌        | 73/484 [01:28<07:44,  1.13s/it]

done with patient sub-02015730
currently working on sub-01498464


 15%|█▌        | 74/484 [01:29<07:39,  1.12s/it]

done with patient sub-01498464
currently working on sub-01713725


 15%|█▌        | 75/484 [01:30<07:51,  1.15s/it]

done with patient sub-01713725
currently working on sub-01744565


 16%|█▌        | 76/484 [01:32<08:24,  1.24s/it]

done with patient sub-01744565
currently working on sub-01414540


 16%|█▌        | 77/484 [01:33<07:59,  1.18s/it]

done with patient sub-01414540
currently working on sub-01871625


 16%|█▌        | 78/484 [01:34<08:18,  1.23s/it]

done with patient sub-01871625
currently working on sub-01098043


 16%|█▋        | 79/484 [01:35<08:08,  1.21s/it]

done with patient sub-01098043
currently working on sub-01707721


 17%|█▋        | 80/484 [01:36<07:50,  1.16s/it]

done with patient sub-01707721
currently working on sub-01874079


 17%|█▋        | 81/484 [01:38<07:46,  1.16s/it]

done with patient sub-01874079
currently working on sub-01732456


 17%|█▋        | 82/484 [01:39<07:44,  1.16s/it]

done with patient sub-01732456
currently working on sub-01457167


 17%|█▋        | 83/484 [01:40<07:37,  1.14s/it]

done with patient sub-01457167
currently working on sub-02066445


 17%|█▋        | 84/484 [01:41<08:23,  1.26s/it]

done with patient sub-02066445
currently working on sub-01391534


 18%|█▊        | 85/484 [01:42<07:57,  1.20s/it]

done with patient sub-01391534
currently working on sub-01332588


 18%|█▊        | 86/484 [01:43<07:40,  1.16s/it]

done with patient sub-01332588
currently working on sub-96004436


 18%|█▊        | 87/484 [01:45<07:26,  1.12s/it]

done with patient sub-96004436
currently working on sub-01015961


 18%|█▊        | 88/484 [01:46<07:15,  1.10s/it]

done with patient sub-01015961
currently working on sub-02190005


 18%|█▊        | 89/484 [01:47<07:14,  1.10s/it]

done with patient sub-02190005
currently working on sub-01718213


 19%|█▉        | 91/484 [01:48<05:28,  1.20it/s]

done with patient sub-01718213
currently working on sub-80004059


 19%|█▉        | 92/484 [01:49<06:21,  1.03it/s]

done with patient sub-80004059
currently working on sub-01695173


 19%|█▉        | 93/484 [01:50<06:32,  1.00s/it]

done with patient sub-01695173
currently working on sub-01117958


 19%|█▉        | 94/484 [01:51<06:36,  1.02s/it]

done with patient sub-01117958
currently working on sub-01881784


 20%|█▉        | 95/484 [01:52<06:37,  1.02s/it]

done with patient sub-01881784
currently working on sub-02177752


 20%|█▉        | 96/484 [01:53<06:54,  1.07s/it]

done with patient sub-02177752
currently working on sub-01654658


 20%|██        | 97/484 [01:55<06:51,  1.06s/it]

done with patient sub-01654658
currently working on sub-01605537


 20%|██        | 98/484 [01:56<06:56,  1.08s/it]

done with patient sub-01605537
currently working on sub-01041137


 20%|██        | 99/484 [01:57<06:50,  1.07s/it]

done with patient sub-01041137
currently working on sub-88000225


 21%|██        | 100/484 [01:58<06:49,  1.07s/it]

done with patient sub-88000225
currently working on sub-02063398


 21%|██        | 101/484 [01:59<06:57,  1.09s/it]

done with patient sub-02063398
currently working on sub-01251946


 21%|██        | 102/484 [02:01<09:11,  1.44s/it]

done with patient sub-01251946
currently working on sub-01657294


 21%|██▏       | 103/484 [02:02<08:53,  1.40s/it]

done with patient sub-01657294
currently working on sub-02137073


 21%|██▏       | 104/484 [02:04<08:16,  1.31s/it]

done with patient sub-02137073
currently working on sub-02164825


 22%|██▏       | 105/484 [02:05<07:48,  1.24s/it]

done with patient sub-02164825
currently working on sub-02119712


 22%|██▏       | 106/484 [02:06<08:03,  1.28s/it]

done with patient sub-02119712
currently working on sub-01729917


 22%|██▏       | 107/484 [02:07<07:38,  1.22s/it]

done with patient sub-01729917
currently working on sub-01207036


 22%|██▏       | 108/484 [02:08<07:19,  1.17s/it]

done with patient sub-01207036
currently working on sub-02090169


 23%|██▎       | 109/484 [02:09<07:05,  1.13s/it]

done with patient sub-02090169
currently working on sub-02137062


 23%|██▎       | 110/484 [02:10<06:58,  1.12s/it]

done with patient sub-02137062
currently working on sub-01812578


 23%|██▎       | 111/484 [02:19<21:23,  3.44s/it]

done with patient sub-01812578
currently working on sub-02145622


 23%|██▎       | 112/484 [02:20<16:48,  2.71s/it]

done with patient sub-02145622
currently working on sub-01852952


 23%|██▎       | 113/484 [02:21<14:02,  2.27s/it]

done with patient sub-01852952
currently working on sub-02199356


 24%|██▎       | 114/484 [02:22<11:46,  1.91s/it]

done with patient sub-02199356
currently working on sub-01609293


 24%|██▍       | 115/484 [02:25<12:45,  2.08s/it]

done with patient sub-01609293
currently working on sub-01854308


 24%|██▍       | 116/484 [02:26<10:53,  1.78s/it]

done with patient sub-01854308
currently working on sub-01681275


 24%|██▍       | 117/484 [02:27<10:07,  1.66s/it]

done with patient sub-01681275
currently working on sub-01961566


 24%|██▍       | 118/484 [02:28<08:59,  1.47s/it]

done with patient sub-01961566
currently working on sub-02115377


 25%|██▍       | 119/484 [02:29<08:06,  1.33s/it]

done with patient sub-02115377
currently working on sub-01607473


 25%|██▍       | 120/484 [02:30<07:36,  1.25s/it]

done with patient sub-01607473
currently working on sub-01465229


 25%|██▌       | 121/484 [02:32<07:23,  1.22s/it]

done with patient sub-01465229
currently working on sub-02116290


 25%|██▌       | 122/484 [02:33<07:13,  1.20s/it]

done with patient sub-02116290
currently working on sub-01377261


 25%|██▌       | 123/484 [02:34<07:07,  1.18s/it]

done with patient sub-01377261
currently working on sub-01083248


 26%|██▌       | 124/484 [02:35<06:55,  1.15s/it]

done with patient sub-01083248
currently working on sub-01005097


 26%|██▌       | 125/484 [02:36<06:43,  1.13s/it]

done with patient sub-01005097
currently working on sub-02172137


 26%|██▌       | 126/484 [02:37<07:04,  1.19s/it]

done with patient sub-02172137
currently working on sub-01201482


 26%|██▌       | 127/484 [02:39<07:13,  1.22s/it]

done with patient sub-01201482
currently working on sub-02153522


 27%|██▋       | 129/484 [02:40<05:13,  1.13it/s]

done with patient sub-02153522
currently working on sub-02094837


 27%|██▋       | 130/484 [02:42<06:49,  1.16s/it]

done with patient sub-02094837
currently working on sub-02063373


 27%|██▋       | 131/484 [02:43<06:41,  1.14s/it]

done with patient sub-02063373
currently working on sub-01489395


 27%|██▋       | 132/484 [02:45<07:55,  1.35s/it]

done with patient sub-01489395
currently working on sub-01695930


 27%|██▋       | 133/484 [02:46<07:23,  1.26s/it]

done with patient sub-01695930
currently working on sub-01288036


 28%|██▊       | 134/484 [02:47<07:02,  1.21s/it]

done with patient sub-01288036
currently working on sub-01387984


 28%|██▊       | 135/484 [02:48<06:55,  1.19s/it]

done with patient sub-01387984
currently working on sub-01600788


 28%|██▊       | 136/484 [02:49<06:58,  1.20s/it]

done with patient sub-01600788
currently working on sub-02034046


 28%|██▊       | 137/484 [02:50<06:42,  1.16s/it]

done with patient sub-02034046
currently working on sub-01125016


 29%|██▊       | 138/484 [02:51<06:29,  1.13s/it]

done with patient sub-01125016
currently working on sub-01311383


 29%|██▊       | 139/484 [02:52<06:35,  1.15s/it]

done with patient sub-01311383
currently working on sub-01649133


 29%|██▉       | 140/484 [02:54<06:25,  1.12s/it]

done with patient sub-01649133
currently working on sub-02026964


 29%|██▉       | 141/484 [02:55<06:31,  1.14s/it]

done with patient sub-02026964
currently working on sub-01340749


 29%|██▉       | 142/484 [02:56<06:28,  1.14s/it]

done with patient sub-01340749
currently working on sub-02015335


 30%|██▉       | 143/484 [02:57<06:22,  1.12s/it]

done with patient sub-02015335
currently working on sub-02183443


 30%|██▉       | 144/484 [02:58<06:20,  1.12s/it]

done with patient sub-02183443
currently working on sub-01550202


 30%|██▉       | 145/484 [02:59<06:15,  1.11s/it]

done with patient sub-01550202
currently working on sub-01405609


 30%|███       | 146/484 [03:00<06:07,  1.09s/it]

done with patient sub-01405609
currently working on sub-01072344


 30%|███       | 147/484 [03:01<06:04,  1.08s/it]

done with patient sub-01072344
currently working on sub-02115365


 31%|███       | 148/484 [03:02<06:00,  1.07s/it]

done with patient sub-02115365
currently working on sub-01373833


 31%|███       | 149/484 [03:07<11:23,  2.04s/it]

done with patient sub-01373833
currently working on sub-01953116


 31%|███       | 150/484 [03:08<09:48,  1.76s/it]

done with patient sub-01953116
currently working on sub-01935938


 31%|███       | 151/484 [03:09<08:42,  1.57s/it]

done with patient sub-01935938
currently working on sub-02031256


 31%|███▏      | 152/484 [03:10<07:56,  1.44s/it]

done with patient sub-02031256
currently working on sub-01220269


 32%|███▏      | 153/484 [03:11<07:22,  1.34s/it]

done with patient sub-01220269
currently working on sub-01801060


 32%|███▏      | 154/484 [03:12<07:06,  1.29s/it]

done with patient sub-01801060
currently working on sub-02086122


 32%|███▏      | 155/484 [03:13<06:49,  1.24s/it]

done with patient sub-02086122
currently working on sub-01710310


 32%|███▏      | 156/484 [03:14<06:30,  1.19s/it]

done with patient sub-01710310
currently working on sub-02071509


 32%|███▏      | 157/484 [03:16<06:25,  1.18s/it]

done with patient sub-02071509
currently working on sub-02094018


 33%|███▎      | 158/484 [03:18<07:47,  1.43s/it]

done with patient sub-02094018
currently working on sub-01331487


 33%|███▎      | 159/484 [03:19<07:23,  1.37s/it]

done with patient sub-01331487
currently working on sub-02082498


 33%|███▎      | 160/484 [03:20<07:01,  1.30s/it]

done with patient sub-02082498
currently working on sub-01415245


 33%|███▎      | 161/484 [03:21<06:36,  1.23s/it]

done with patient sub-01415245
currently working on sub-01530724


 33%|███▎      | 162/484 [03:22<06:21,  1.19s/it]

done with patient sub-01530724
currently working on sub-01423083


 34%|███▎      | 163/484 [03:23<06:08,  1.15s/it]

done with patient sub-01423083
currently working on sub-01307298


 34%|███▍      | 164/484 [03:24<06:10,  1.16s/it]

done with patient sub-01307298
currently working on sub-02163033


 34%|███▍      | 165/484 [03:25<06:07,  1.15s/it]

done with patient sub-02163033
currently working on sub-01201117


 34%|███▍      | 166/484 [03:27<06:19,  1.19s/it]

done with patient sub-01201117
currently working on sub-02167792


 35%|███▍      | 167/484 [03:28<06:19,  1.20s/it]

done with patient sub-02167792
currently working on sub-01674416


 35%|███▍      | 168/484 [03:29<06:07,  1.16s/it]

done with patient sub-01674416
currently working on sub-01108350


 35%|███▍      | 169/484 [03:30<05:57,  1.14s/it]

done with patient sub-01108350
currently working on sub-01619086


 35%|███▌      | 170/484 [03:31<06:08,  1.17s/it]

done with patient sub-01619086
currently working on sub-02092748


 35%|███▌      | 171/484 [03:36<10:54,  2.09s/it]

done with patient sub-02092748
currently working on sub-01205171


 36%|███▌      | 172/484 [03:37<09:22,  1.80s/it]

done with patient sub-01205171
currently working on sub-01705952


 36%|███▌      | 173/484 [03:39<10:00,  1.93s/it]

done with patient sub-01705952
currently working on sub-02018743


 36%|███▌      | 174/484 [03:41<09:36,  1.86s/it]

done with patient sub-02018743
currently working on sub-02073121


 36%|███▌      | 175/484 [03:42<08:21,  1.62s/it]

done with patient sub-02073121
currently working on sub-01483723


 36%|███▋      | 176/484 [03:43<07:54,  1.54s/it]

done with patient sub-01483723
currently working on sub-02071305


 37%|███▋      | 177/484 [03:44<07:10,  1.40s/it]

done with patient sub-02071305
currently working on sub-01548397


 37%|███▋      | 178/484 [03:45<06:42,  1.32s/it]

done with patient sub-01548397
currently working on sub-01109318


 37%|███▋      | 179/484 [03:46<06:26,  1.27s/it]

done with patient sub-01109318
currently working on sub-01456719


 37%|███▋      | 180/484 [03:48<06:24,  1.26s/it]

done with patient sub-01456719
currently working on sub-01569328


 37%|███▋      | 181/484 [03:49<06:25,  1.27s/it]

done with patient sub-01569328
currently working on sub-01496608


 38%|███▊      | 182/484 [03:51<06:56,  1.38s/it]

done with patient sub-01496608
currently working on sub-01400779


 38%|███▊      | 183/484 [03:52<06:26,  1.28s/it]

done with patient sub-01400779
currently working on sub-01431720


 38%|███▊      | 184/484 [03:53<06:12,  1.24s/it]

done with patient sub-01431720
currently working on sub-01573094


 38%|███▊      | 185/484 [03:54<06:21,  1.28s/it]

done with patient sub-01573094
currently working on sub-01879950


 38%|███▊      | 186/484 [03:56<07:32,  1.52s/it]

done with patient sub-01879950
currently working on sub-01420310


 39%|███▊      | 187/484 [03:57<07:02,  1.42s/it]

done with patient sub-01420310
currently working on sub-01483116


 39%|███▉      | 188/484 [03:59<06:35,  1.34s/it]

done with patient sub-01483116
currently working on sub-01713022


 39%|███▉      | 189/484 [04:00<06:47,  1.38s/it]

done with patient sub-01713022
currently working on sub-02197683


 39%|███▉      | 190/484 [04:01<06:22,  1.30s/it]

done with patient sub-02197683
currently working on sub-01499528


 39%|███▉      | 191/484 [04:02<06:00,  1.23s/it]

done with patient sub-01499528
currently working on sub-01478990


 40%|███▉      | 192/484 [04:04<06:26,  1.32s/it]

done with patient sub-01478990
currently working on sub-01578955


 40%|███▉      | 193/484 [04:05<06:03,  1.25s/it]

done with patient sub-01578955
currently working on sub-01652130


 40%|████      | 194/484 [04:06<05:52,  1.21s/it]

done with patient sub-01652130
currently working on sub-01706562


 40%|████      | 195/484 [04:07<05:38,  1.17s/it]

done with patient sub-01706562
currently working on sub-01390721


 40%|████      | 196/484 [04:08<05:49,  1.21s/it]

done with patient sub-01390721
currently working on sub-01985065


 41%|████      | 197/484 [04:09<05:31,  1.16s/it]

done with patient sub-01985065
currently working on sub-01414189


 41%|████      | 198/484 [04:11<05:32,  1.16s/it]

done with patient sub-01414189
currently working on sub-01138456


 41%|████      | 199/484 [04:12<05:53,  1.24s/it]

done with patient sub-01138456
currently working on sub-02113470


 41%|████▏     | 200/484 [04:31<31:00,  6.55s/it]

done with patient sub-02113470
currently working on sub-02134991


 42%|████▏     | 201/484 [04:34<26:02,  5.52s/it]

done with patient sub-02134991
currently working on sub-01760947


 42%|████▏     | 202/484 [04:36<20:45,  4.42s/it]

done with patient sub-01760947
currently working on sub-02070606


 42%|████▏     | 203/484 [04:37<16:18,  3.48s/it]

done with patient sub-02070606
currently working on sub-02014467


 42%|████▏     | 204/484 [04:39<13:18,  2.85s/it]

done with patient sub-02014467
currently working on sub-01501379


 42%|████▏     | 205/484 [04:40<10:48,  2.32s/it]

done with patient sub-01501379
currently working on sub-02209727


 43%|████▎     | 206/484 [04:41<09:44,  2.10s/it]

done with patient sub-02209727
currently working on sub-01979997


 43%|████▎     | 207/484 [04:43<08:39,  1.88s/it]

done with patient sub-01979997
currently working on sub-01699532


 43%|████▎     | 208/484 [04:44<07:34,  1.65s/it]

done with patient sub-01699532
currently working on sub-01695080


 43%|████▎     | 209/484 [04:45<06:59,  1.52s/it]

done with patient sub-01695080
currently working on sub-01087386


 43%|████▎     | 210/484 [04:46<06:22,  1.40s/it]

done with patient sub-01087386
currently working on sub-01122863


 44%|████▎     | 211/484 [04:47<06:23,  1.41s/it]

done with patient sub-01122863
currently working on sub-02106388


 44%|████▍     | 212/484 [04:49<05:54,  1.30s/it]

done with patient sub-02106388
currently working on sub-01152379


 44%|████▍     | 213/484 [04:50<05:32,  1.23s/it]

done with patient sub-01152379
currently working on sub-02055312


 44%|████▍     | 214/484 [04:51<05:27,  1.21s/it]

done with patient sub-02055312
currently working on sub-02145870


 44%|████▍     | 215/484 [04:52<05:23,  1.20s/it]

done with patient sub-02145870
currently working on sub-02036053


 45%|████▍     | 216/484 [04:53<05:36,  1.26s/it]

done with patient sub-02036053
currently working on sub-02120805


 45%|████▍     | 217/484 [04:55<05:51,  1.32s/it]

done with patient sub-02120805
currently working on sub-01395836


 45%|████▌     | 218/484 [04:56<05:33,  1.26s/it]

done with patient sub-01395836
currently working on sub-01914558


 45%|████▌     | 220/484 [04:57<04:11,  1.05it/s]

done with patient sub-01914558
currently working on sub-01892684


 46%|████▌     | 221/484 [04:59<04:43,  1.08s/it]

done with patient sub-01892684
currently working on sub-01660211


 46%|████▌     | 223/484 [05:00<03:43,  1.17it/s]

done with patient sub-01660211
currently working on sub-01486069


 46%|████▋     | 224/484 [05:01<04:01,  1.08it/s]

done with patient sub-01486069
currently working on sub-01583797


 47%|████▋     | 226/484 [05:02<03:21,  1.28it/s]

done with patient sub-01583797
currently working on sub-01936520


 47%|████▋     | 227/484 [05:03<03:45,  1.14it/s]

done with patient sub-01936520
currently working on sub-01594137


 47%|████▋     | 228/484 [05:04<04:01,  1.06it/s]

done with patient sub-01594137
currently working on sub-01882989


 47%|████▋     | 229/484 [05:05<04:11,  1.01it/s]

done with patient sub-01882989
currently working on sub-01021993


 48%|████▊     | 230/484 [05:07<04:33,  1.08s/it]

done with patient sub-01021993
currently working on sub-02063986


 48%|████▊     | 231/484 [05:08<04:37,  1.10s/it]

done with patient sub-02063986
currently working on sub-01804484


 48%|████▊     | 232/484 [05:11<06:31,  1.55s/it]

done with patient sub-01804484
currently working on sub-01830168


 48%|████▊     | 233/484 [05:12<05:55,  1.42s/it]

done with patient sub-01830168
currently working on sub-02015217


 48%|████▊     | 234/484 [05:13<06:09,  1.48s/it]

done with patient sub-02015217
currently working on sub-01707275


 49%|████▊     | 235/484 [05:14<05:38,  1.36s/it]

done with patient sub-01707275
currently working on sub-02070580


 49%|████▉     | 236/484 [05:15<05:16,  1.28s/it]

done with patient sub-02070580
currently working on sub-02080563


 49%|████▉     | 237/484 [05:17<05:04,  1.23s/it]

done with patient sub-02080563
currently working on sub-01483526


 49%|████▉     | 238/484 [05:18<04:52,  1.19s/it]

done with patient sub-01483526
currently working on sub-02167890


 49%|████▉     | 239/484 [05:19<04:58,  1.22s/it]

done with patient sub-02167890
currently working on sub-01269967


 50%|████▉     | 240/484 [05:20<04:53,  1.20s/it]

done with patient sub-01269967
currently working on sub-01769144


 50%|████▉     | 241/484 [05:21<04:43,  1.17s/it]

done with patient sub-01769144
currently working on sub-01452858


 50%|█████     | 242/484 [05:22<04:43,  1.17s/it]

done with patient sub-01452858
currently working on sub-01890298


 50%|█████     | 243/484 [05:24<04:40,  1.16s/it]

done with patient sub-01890298
currently working on sub-01064662


 50%|█████     | 244/484 [05:25<04:37,  1.16s/it]

done with patient sub-01064662
currently working on sub-02064363


 51%|█████     | 245/484 [05:26<04:49,  1.21s/it]

done with patient sub-02064363
currently working on sub-01456959


 51%|█████     | 246/484 [05:27<04:39,  1.17s/it]

done with patient sub-01456959
currently working on sub-01666008


 51%|█████     | 247/484 [05:28<04:37,  1.17s/it]

done with patient sub-01666008
currently working on sub-01710250


 51%|█████     | 248/484 [05:29<04:35,  1.17s/it]

done with patient sub-01710250
currently working on sub-02135803


 51%|█████▏    | 249/484 [05:32<06:44,  1.72s/it]

done with patient sub-02135803
currently working on sub-01492723


 52%|█████▏    | 250/484 [05:34<06:13,  1.60s/it]

done with patient sub-01492723
currently working on sub-01516618


 52%|█████▏    | 251/484 [05:37<08:34,  2.21s/it]

done with patient sub-01516618
currently working on sub-01521835


 52%|█████▏    | 252/484 [05:38<07:12,  1.86s/it]

done with patient sub-01521835
currently working on sub-01641960


 52%|█████▏    | 253/484 [05:40<06:43,  1.75s/it]

done with patient sub-01641960
currently working on sub-01773716


 52%|█████▏    | 254/484 [05:41<05:53,  1.54s/it]

done with patient sub-01773716
currently working on sub-01584596


 53%|█████▎    | 255/484 [05:42<05:22,  1.41s/it]

done with patient sub-01584596
currently working on sub-01699419


 53%|█████▎    | 256/484 [05:43<05:11,  1.36s/it]

done with patient sub-01699419
currently working on sub-02090905


 53%|█████▎    | 257/484 [05:44<04:48,  1.27s/it]

done with patient sub-02090905
currently working on sub-01025630


 53%|█████▎    | 258/484 [05:45<04:36,  1.22s/it]

done with patient sub-01025630
currently working on sub-02127770


 54%|█████▎    | 259/484 [05:49<07:02,  1.88s/it]

done with patient sub-02127770
currently working on sub-01670714


 54%|█████▎    | 260/484 [05:50<06:06,  1.63s/it]

done with patient sub-01670714
currently working on sub-01393875


 54%|█████▍    | 261/484 [05:51<05:25,  1.46s/it]

done with patient sub-01393875
currently working on sub-01982853


 54%|█████▍    | 262/484 [05:52<04:56,  1.34s/it]

done with patient sub-01982853
currently working on sub-01673701


 54%|█████▍    | 263/484 [05:53<04:41,  1.27s/it]

done with patient sub-01673701
currently working on sub-02073198


 55%|█████▍    | 264/484 [05:54<04:21,  1.19s/it]

done with patient sub-02073198
currently working on sub-01673666


 55%|█████▍    | 265/484 [05:55<04:16,  1.17s/it]

done with patient sub-01673666
currently working on sub-02051037


 55%|█████▍    | 266/484 [05:57<04:16,  1.18s/it]

done with patient sub-02051037
currently working on sub-01005630


 55%|█████▌    | 267/484 [05:58<04:15,  1.18s/it]

done with patient sub-01005630
currently working on sub-02185066


 55%|█████▌    | 268/484 [05:59<04:05,  1.14s/it]

done with patient sub-02185066
currently working on sub-01021714


 56%|█████▌    | 269/484 [06:00<04:17,  1.20s/it]

done with patient sub-01021714
currently working on sub-02071087


 56%|█████▌    | 270/484 [06:01<04:12,  1.18s/it]

done with patient sub-02071087
currently working on sub-01188297


 56%|█████▌    | 271/484 [06:02<04:02,  1.14s/it]

done with patient sub-01188297
currently working on sub-01924748


 56%|█████▌    | 272/484 [06:03<04:00,  1.13s/it]

done with patient sub-01924748
currently working on sub-01476909


 56%|█████▋    | 273/484 [06:05<04:01,  1.15s/it]

done with patient sub-01476909
currently working on sub-01819252


 57%|█████▋    | 274/484 [06:06<03:55,  1.12s/it]

done with patient sub-01819252
currently working on sub-80011453


 57%|█████▋    | 275/484 [06:07<03:52,  1.11s/it]

done with patient sub-80011453
currently working on sub-01261127


 57%|█████▋    | 276/484 [06:08<03:55,  1.13s/it]

done with patient sub-01261127
currently working on sub-01696845


 57%|█████▋    | 277/484 [06:09<04:06,  1.19s/it]

done with patient sub-01696845
currently working on sub-01659187


 57%|█████▋    | 278/484 [06:10<04:01,  1.17s/it]

done with patient sub-01659187
currently working on sub-01650072


 58%|█████▊    | 279/484 [06:11<03:53,  1.14s/it]

done with patient sub-01650072
currently working on sub-01106844


 58%|█████▊    | 280/484 [07:15<1:07:14, 19.78s/it]

done with patient sub-01106844
currently working on sub-01377175


 58%|█████▊    | 281/484 [07:16<47:56, 14.17s/it]  

done with patient sub-01377175
currently working on sub-02019520


 58%|█████▊    | 283/484 [07:17<26:23,  7.88s/it]

done with patient sub-02019520
currently working on sub-01038520


 59%|█████▊    | 284/484 [07:18<20:40,  6.20s/it]

done with patient sub-01038520
currently working on sub-93002557


 59%|█████▉    | 285/484 [07:19<16:07,  4.86s/it]

done with patient sub-93002557
currently working on sub-02181503


 59%|█████▉    | 286/484 [07:20<12:41,  3.85s/it]

done with patient sub-02181503
currently working on sub-02095961


 59%|█████▉    | 287/484 [07:23<11:46,  3.59s/it]

done with patient sub-02095961
currently working on sub-01805334


 60%|█████▉    | 288/484 [07:24<09:31,  2.92s/it]

done with patient sub-01805334
currently working on sub-01281168


 60%|█████▉    | 289/484 [07:25<07:49,  2.41s/it]

done with patient sub-01281168
currently working on sub-01957841


 60%|█████▉    | 290/484 [07:26<06:28,  2.00s/it]

done with patient sub-01957841
currently working on sub-02105939


 60%|██████    | 291/484 [07:32<09:22,  2.92s/it]

done with patient sub-02105939
currently working on sub-01373703


 60%|██████    | 292/484 [07:33<07:40,  2.40s/it]

done with patient sub-01373703
currently working on sub-01435731


 61%|██████    | 293/484 [07:34<06:27,  2.03s/it]

done with patient sub-01435731
currently working on sub-01288245


 61%|██████    | 294/484 [07:35<05:30,  1.74s/it]

done with patient sub-01288245
currently working on sub-02031868


 61%|██████    | 295/484 [07:36<04:59,  1.58s/it]

done with patient sub-02031868
currently working on sub-01130173


 61%|██████    | 296/484 [07:37<04:35,  1.46s/it]

done with patient sub-01130173
currently working on sub-01798755


 61%|██████▏   | 297/484 [07:39<04:24,  1.41s/it]

done with patient sub-01798755
currently working on sub-01502083


 62%|██████▏   | 298/484 [07:40<04:29,  1.45s/it]

done with patient sub-01502083
currently working on sub-01562247


 62%|██████▏   | 299/484 [07:41<04:16,  1.38s/it]

done with patient sub-01562247
currently working on sub-01686968


 62%|██████▏   | 300/484 [07:43<04:01,  1.31s/it]

done with patient sub-01686968
currently working on sub-01314225


 62%|██████▏   | 301/484 [07:44<03:45,  1.23s/it]

done with patient sub-01314225
currently working on sub-01455312


 62%|██████▏   | 302/484 [07:45<04:04,  1.34s/it]

done with patient sub-01455312
currently working on sub-02146286


 63%|██████▎   | 303/484 [07:46<03:48,  1.26s/it]

done with patient sub-02146286
currently working on sub-01496804


 63%|██████▎   | 304/484 [07:47<03:43,  1.24s/it]

done with patient sub-01496804
currently working on sub-90003334


 63%|██████▎   | 305/484 [07:49<03:32,  1.18s/it]

done with patient sub-90003334
currently working on sub-01031243


 63%|██████▎   | 306/484 [07:50<03:28,  1.17s/it]

done with patient sub-01031243
currently working on sub-02036130


 63%|██████▎   | 307/484 [07:51<03:27,  1.17s/it]

done with patient sub-02036130
currently working on sub-02174928


 64%|██████▎   | 308/484 [08:21<28:49,  9.83s/it]

done with patient sub-02174928
currently working on sub-01358619


 64%|██████▍   | 309/484 [08:22<21:24,  7.34s/it]

done with patient sub-01358619
currently working on sub-01164986


 64%|██████▍   | 310/484 [08:24<15:56,  5.50s/it]

done with patient sub-01164986
currently working on sub-02020169


 64%|██████▍   | 311/484 [08:25<12:00,  4.16s/it]

done with patient sub-02020169
currently working on sub-01933711


 64%|██████▍   | 312/484 [08:26<09:15,  3.23s/it]

done with patient sub-01933711
currently working on sub-01164049


 65%|██████▍   | 313/484 [08:27<07:21,  2.58s/it]

done with patient sub-01164049
currently working on sub-01691369


 65%|██████▍   | 314/484 [08:28<06:00,  2.12s/it]

done with patient sub-01691369
currently working on sub-02128777


 65%|██████▌   | 315/484 [08:29<05:08,  1.82s/it]

done with patient sub-02128777
currently working on sub-02197114


 65%|██████▌   | 316/484 [08:31<04:53,  1.74s/it]

done with patient sub-02197114
currently working on sub-01056598


 65%|██████▌   | 317/484 [08:34<06:40,  2.40s/it]

done with patient sub-01056598
currently working on sub-02021781


 66%|██████▌   | 318/484 [08:36<05:31,  2.00s/it]

done with patient sub-02021781
currently working on sub-01763867


 66%|██████▌   | 320/484 [08:37<03:39,  1.34s/it]

done with patient sub-01763867
currently working on sub-01792771


 66%|██████▋   | 321/484 [08:38<03:26,  1.27s/it]

done with patient sub-01792771
currently working on sub-01960441


 67%|██████▋   | 322/484 [08:39<03:18,  1.22s/it]

done with patient sub-01960441
currently working on sub-01936903


 67%|██████▋   | 323/484 [08:40<03:09,  1.18s/it]

done with patient sub-01936903
currently working on sub-02104370


 67%|██████▋   | 324/484 [08:41<03:15,  1.22s/it]

done with patient sub-02104370
currently working on sub-01288896


 67%|██████▋   | 325/484 [08:42<03:14,  1.22s/it]

done with patient sub-01288896
currently working on sub-01514331


 67%|██████▋   | 326/484 [08:43<03:06,  1.18s/it]

done with patient sub-01514331
currently working on sub-01542729


 68%|██████▊   | 327/484 [08:45<03:06,  1.19s/it]

done with patient sub-01542729
currently working on sub-01572564


 68%|██████▊   | 328/484 [08:46<02:59,  1.15s/it]

done with patient sub-01572564
currently working on sub-01169240


 68%|██████▊   | 329/484 [08:47<02:55,  1.13s/it]

done with patient sub-01169240
currently working on sub-95001254


 68%|██████▊   | 331/484 [08:48<02:11,  1.16it/s]

done with patient sub-95001254
currently working on sub-01384142


 69%|██████▊   | 332/484 [08:49<02:29,  1.02it/s]

done with patient sub-01384142
currently working on sub-02014068


 69%|██████▉   | 333/484 [08:50<02:33,  1.02s/it]

done with patient sub-02014068
currently working on sub-02196769


 69%|██████▉   | 334/484 [08:53<03:39,  1.46s/it]

done with patient sub-02196769
currently working on sub-02011152


 69%|██████▉   | 335/484 [08:54<03:20,  1.35s/it]

done with patient sub-02011152
currently working on sub-01071055


 69%|██████▉   | 336/484 [08:55<03:07,  1.27s/it]

done with patient sub-01071055
currently working on sub-01677324


 70%|██████▉   | 337/484 [08:57<03:31,  1.44s/it]

done with patient sub-01677324
currently working on sub-01781732


 70%|██████▉   | 338/484 [08:58<03:13,  1.33s/it]

done with patient sub-01781732
currently working on sub-02188930


 70%|███████   | 339/484 [08:59<03:10,  1.32s/it]

done with patient sub-02188930
currently working on sub-02087023


 70%|███████   | 340/484 [09:00<02:58,  1.24s/it]

done with patient sub-02087023
currently working on sub-01409764


 70%|███████   | 341/484 [09:02<02:53,  1.21s/it]

done with patient sub-01409764
currently working on sub-01150136


 71%|███████   | 342/484 [09:03<03:06,  1.31s/it]

done with patient sub-01150136
currently working on sub-01543367


 71%|███████   | 343/484 [09:04<02:53,  1.23s/it]

done with patient sub-01543367
currently working on sub-01616767


 71%|███████   | 344/484 [09:05<02:45,  1.18s/it]

done with patient sub-01616767
currently working on sub-01905848


 71%|███████▏  | 345/484 [09:06<02:38,  1.14s/it]

done with patient sub-01905848
currently working on sub-01969755


 71%|███████▏  | 346/484 [09:07<02:39,  1.16s/it]

done with patient sub-01969755
currently working on sub-01009590


 72%|███████▏  | 347/484 [09:09<02:34,  1.13s/it]

done with patient sub-01009590
currently working on sub-01905692


 72%|███████▏  | 348/484 [09:10<02:31,  1.12s/it]

done with patient sub-01905692
currently working on sub-90001992


 72%|███████▏  | 349/484 [09:11<02:32,  1.13s/it]

done with patient sub-90001992
currently working on sub-01796937


 72%|███████▏  | 350/484 [09:12<02:27,  1.10s/it]

done with patient sub-01796937
currently working on sub-01835095


 73%|███████▎  | 351/484 [09:13<02:25,  1.09s/it]

done with patient sub-01835095
currently working on sub-01357275


 73%|███████▎  | 352/484 [09:14<02:23,  1.08s/it]

done with patient sub-01357275
currently working on sub-02172003


 73%|███████▎  | 354/484 [09:15<01:49,  1.19it/s]

done with patient sub-02172003
currently working on sub-02095181


 73%|███████▎  | 355/484 [09:16<02:02,  1.06it/s]

done with patient sub-02095181
currently working on sub-02084961


 74%|███████▎  | 356/484 [09:17<02:05,  1.02it/s]

done with patient sub-02084961
currently working on sub-02126982


 74%|███████▍  | 357/484 [09:18<02:06,  1.00it/s]

done with patient sub-02126982
currently working on sub-01762556


 74%|███████▍  | 358/484 [09:19<02:07,  1.01s/it]

done with patient sub-01762556
currently working on sub-96003928


 74%|███████▍  | 359/484 [09:21<02:10,  1.04s/it]

done with patient sub-96003928
currently working on sub-01022787


 74%|███████▍  | 360/484 [09:22<02:11,  1.06s/it]

done with patient sub-01022787
currently working on sub-01703264


 75%|███████▍  | 361/484 [09:23<02:10,  1.06s/it]

done with patient sub-01703264
currently working on sub-01882333


 75%|███████▍  | 362/484 [09:24<02:24,  1.19s/it]

done with patient sub-01882333
currently working on sub-01876862


 75%|███████▌  | 363/484 [09:25<02:18,  1.15s/it]

done with patient sub-01876862
currently working on sub-01755816


 75%|███████▌  | 364/484 [09:27<02:28,  1.23s/it]

done with patient sub-01755816
currently working on sub-01190670


 75%|███████▌  | 365/484 [09:28<02:22,  1.20s/it]

done with patient sub-01190670
currently working on sub-02019676


 76%|███████▌  | 366/484 [09:29<02:18,  1.17s/it]

done with patient sub-02019676
currently working on sub-01709242


 76%|███████▌  | 367/484 [09:30<02:13,  1.14s/it]

done with patient sub-01709242
currently working on sub-01981993


 76%|███████▌  | 368/484 [09:31<02:11,  1.13s/it]

done with patient sub-01981993
currently working on sub-01381621


 76%|███████▌  | 369/484 [09:32<02:10,  1.14s/it]

done with patient sub-01381621
currently working on sub-01492604


 76%|███████▋  | 370/484 [09:39<05:30,  2.90s/it]

done with patient sub-01492604
currently working on sub-01199093


 77%|███████▋  | 371/484 [09:40<04:27,  2.37s/it]

done with patient sub-01199093
currently working on sub-01432274


 77%|███████▋  | 372/484 [09:42<03:42,  1.99s/it]

done with patient sub-01432274
currently working on sub-01419998


 77%|███████▋  | 373/484 [09:43<03:09,  1.71s/it]

done with patient sub-01419998
currently working on sub-01402283


 77%|███████▋  | 374/484 [09:44<02:52,  1.57s/it]

done with patient sub-01402283
currently working on sub-01189050


 77%|███████▋  | 375/484 [09:45<02:36,  1.43s/it]

done with patient sub-01189050
currently working on sub-01885520


 78%|███████▊  | 376/484 [09:46<02:24,  1.34s/it]

done with patient sub-01885520
currently working on sub-02132336


 78%|███████▊  | 377/484 [09:47<02:13,  1.25s/it]

done with patient sub-02132336
currently working on sub-01515235


 78%|███████▊  | 378/484 [09:48<02:13,  1.26s/it]

done with patient sub-01515235
currently working on sub-01706146


 78%|███████▊  | 379/484 [09:50<02:19,  1.33s/it]

done with patient sub-01706146
currently working on sub-02097980


 79%|███████▊  | 380/484 [09:51<02:11,  1.26s/it]

done with patient sub-02097980
currently working on sub-01421533


 79%|███████▊  | 381/484 [09:52<02:06,  1.22s/it]

done with patient sub-01421533
currently working on sub-01596127


 79%|███████▉  | 382/484 [09:54<02:11,  1.29s/it]

done with patient sub-01596127
currently working on sub-01545797


 79%|███████▉  | 383/484 [09:55<02:04,  1.23s/it]

done with patient sub-01545797
currently working on sub-01450871


 79%|███████▉  | 384/484 [09:56<02:00,  1.21s/it]

done with patient sub-01450871
currently working on sub-01434869


 80%|███████▉  | 385/484 [09:57<01:54,  1.16s/it]

done with patient sub-01434869
currently working on sub-01518885


 80%|███████▉  | 386/484 [09:58<01:50,  1.13s/it]

done with patient sub-01518885
currently working on sub-01117914


 80%|███████▉  | 387/484 [09:59<01:58,  1.22s/it]

done with patient sub-01117914
currently working on sub-01551183


 80%|████████  | 388/484 [10:01<02:01,  1.27s/it]

done with patient sub-01551183
currently working on sub-02138280


 80%|████████  | 389/484 [10:02<02:05,  1.33s/it]

done with patient sub-02138280
currently working on sub-02066389


 81%|████████  | 390/484 [10:03<01:56,  1.24s/it]

done with patient sub-02066389
currently working on sub-01961554


 81%|████████  | 391/484 [10:04<01:52,  1.21s/it]

done with patient sub-01961554
currently working on sub-02110064


 81%|████████  | 392/484 [10:05<01:48,  1.18s/it]

done with patient sub-02110064
currently working on sub-01943022


 81%|████████  | 393/484 [10:07<02:04,  1.37s/it]

done with patient sub-01943022
currently working on sub-01130856


 81%|████████▏ | 394/484 [10:08<01:55,  1.28s/it]

done with patient sub-01130856
currently working on sub-02094355


 82%|████████▏ | 395/484 [10:09<01:48,  1.22s/it]

done with patient sub-02094355
currently working on sub-01131702


 82%|████████▏ | 396/484 [10:11<01:44,  1.18s/it]

done with patient sub-01131702
currently working on sub-01484016


 82%|████████▏ | 397/484 [10:12<01:39,  1.15s/it]

done with patient sub-01484016
currently working on sub-01410235


 82%|████████▏ | 398/484 [10:17<03:30,  2.44s/it]

done with patient sub-01410235
currently working on sub-02100576
No metastases found in /Users/LennartPhilipp/Desktop/Uni/Prowiss/Datensatz_RGB/preprocessed_n4_brainlesion_percentile_20240612-083743/sub-02100576/perc_normalized/sub-02100576_t1c_perc_normalized.nii.gz
No metastases found in /Users/LennartPhilipp/Desktop/Uni/Prowiss/Datensatz_RGB/preprocessed_n4_brainlesion_percentile_20240612-083743/sub-02100576/perc_normalized/sub-02100576_fla_perc_normalized.nii.gz
No metastases found in /Users/LennartPhilipp/Desktop/Uni/Prowiss/Datensatz_RGB/preprocessed_n4_brainlesion_percentile_20240612-083743/sub-02100576/perc_normalized/sub-02100576_t2_perc_normalized.nii.gz


 82%|████████▏ | 399/484 [10:18<02:50,  2.01s/it]

No metastases found in /Users/LennartPhilipp/Desktop/Uni/Prowiss/Datensatz_RGB/preprocessed_n4_brainlesion_percentile_20240612-083743/sub-02100576/perc_normalized/sub-02100576_t1_perc_normalized.nii.gz
done with patient sub-02100576
currently working on sub-01241505


 83%|████████▎ | 400/484 [10:21<03:05,  2.20s/it]

done with patient sub-01241505
currently working on sub-02142561


 83%|████████▎ | 401/484 [10:23<03:08,  2.27s/it]

done with patient sub-02142561
currently working on sub-01214417


 83%|████████▎ | 402/484 [10:24<02:37,  1.93s/it]

done with patient sub-01214417
currently working on sub-01668785


 83%|████████▎ | 403/484 [10:25<02:14,  1.67s/it]

done with patient sub-01668785
currently working on sub-01958155


 83%|████████▎ | 404/484 [10:26<01:58,  1.48s/it]

done with patient sub-01958155
currently working on sub-01521599


 84%|████████▎ | 405/484 [10:27<01:47,  1.36s/it]

done with patient sub-01521599
currently working on sub-01549022


 84%|████████▍ | 406/484 [10:29<01:39,  1.28s/it]

done with patient sub-01549022
currently working on sub-01099901


 84%|████████▍ | 407/484 [10:30<01:36,  1.25s/it]

done with patient sub-01099901
currently working on sub-90003562


 84%|████████▍ | 408/484 [10:31<01:31,  1.20s/it]

done with patient sub-90003562
currently working on sub-01288350


 85%|████████▍ | 409/484 [10:32<01:32,  1.23s/it]

done with patient sub-01288350
currently working on sub-01908576


 85%|████████▍ | 411/484 [10:33<01:07,  1.09it/s]

done with patient sub-01908576
currently working on sub-01349100


 85%|████████▌ | 412/484 [10:34<01:11,  1.01it/s]

done with patient sub-01349100
currently working on sub-01893873


 85%|████████▌ | 413/484 [10:36<01:15,  1.06s/it]

done with patient sub-01893873
currently working on sub-01111974


 86%|████████▌ | 414/484 [10:40<02:24,  2.06s/it]

done with patient sub-01111974
currently working on sub-99000041


 86%|████████▌ | 415/484 [10:42<02:03,  1.79s/it]

done with patient sub-99000041
currently working on sub-02026140


 86%|████████▌ | 416/484 [10:43<01:47,  1.58s/it]

done with patient sub-02026140
currently working on sub-01979317


 86%|████████▌ | 417/484 [10:44<01:38,  1.48s/it]

done with patient sub-01979317
currently working on sub-02178883


 86%|████████▋ | 418/484 [10:45<01:30,  1.37s/it]

done with patient sub-02178883
currently working on sub-02190209


 87%|████████▋ | 419/484 [10:50<02:37,  2.43s/it]

done with patient sub-02190209
currently working on sub-01262362


 87%|████████▋ | 420/484 [10:51<02:10,  2.03s/it]

done with patient sub-01262362
currently working on sub-02148372


 87%|████████▋ | 421/484 [10:53<02:17,  2.18s/it]

done with patient sub-02148372
currently working on sub-01702596


 87%|████████▋ | 422/484 [10:55<01:56,  1.87s/it]

done with patient sub-01702596
currently working on sub-01480742


 87%|████████▋ | 423/484 [10:56<01:41,  1.67s/it]

done with patient sub-01480742
currently working on sub-01443624


 88%|████████▊ | 424/484 [10:57<01:35,  1.60s/it]

done with patient sub-01443624
currently working on sub-02074050


 88%|████████▊ | 425/484 [10:58<01:26,  1.47s/it]

done with patient sub-02074050
currently working on sub-02085355


 88%|████████▊ | 426/484 [11:00<01:24,  1.46s/it]

done with patient sub-02085355
currently working on sub-02139997


 88%|████████▊ | 427/484 [11:01<01:19,  1.40s/it]

done with patient sub-02139997
currently working on sub-01147272


 88%|████████▊ | 428/484 [11:02<01:16,  1.36s/it]

done with patient sub-01147272
currently working on sub-01196057


 89%|████████▊ | 429/484 [11:04<01:10,  1.28s/it]

done with patient sub-01196057
currently working on sub-02010452


 89%|████████▉ | 430/484 [11:05<01:07,  1.24s/it]

done with patient sub-02010452
currently working on sub-01864584


 89%|████████▉ | 431/484 [11:06<01:11,  1.34s/it]

done with patient sub-01864584
currently working on sub-02088404


 89%|████████▉ | 432/484 [11:08<01:12,  1.39s/it]

done with patient sub-02088404
currently working on sub-01497790


 89%|████████▉ | 433/484 [11:09<01:06,  1.30s/it]

done with patient sub-01497790
currently working on sub-01547588


 90%|████████▉ | 434/484 [11:11<01:11,  1.44s/it]

done with patient sub-01547588
currently working on sub-02168956


 90%|████████▉ | 435/484 [11:12<01:11,  1.45s/it]

done with patient sub-02168956
currently working on sub-02089657


 90%|█████████ | 436/484 [11:13<01:04,  1.34s/it]

done with patient sub-02089657
currently working on sub-01978091


 90%|█████████ | 437/484 [11:14<00:59,  1.26s/it]

done with patient sub-01978091
currently working on sub-01362907


 90%|█████████ | 438/484 [11:15<00:56,  1.23s/it]

done with patient sub-01362907
currently working on sub-02122538


 91%|█████████ | 439/484 [11:16<00:53,  1.18s/it]

done with patient sub-02122538
currently working on sub-01410317


 91%|█████████ | 440/484 [11:18<00:52,  1.19s/it]

done with patient sub-01410317
currently working on sub-01119720


 91%|█████████ | 441/484 [11:19<00:52,  1.22s/it]

done with patient sub-01119720
currently working on sub-01231700


 91%|█████████▏| 442/484 [11:20<00:49,  1.18s/it]

done with patient sub-01231700
currently working on sub-01441531


 92%|█████████▏| 443/484 [11:21<00:48,  1.19s/it]

done with patient sub-01441531
currently working on sub-02095303


 92%|█████████▏| 444/484 [11:22<00:46,  1.15s/it]

done with patient sub-02095303
currently working on sub-01006290


 92%|█████████▏| 445/484 [11:23<00:44,  1.14s/it]

done with patient sub-01006290
currently working on sub-02096374


 92%|█████████▏| 446/484 [11:25<00:43,  1.13s/it]

done with patient sub-02096374
currently working on sub-01792136


 92%|█████████▏| 447/484 [11:26<00:41,  1.12s/it]

done with patient sub-01792136
currently working on sub-01661279


 93%|█████████▎| 448/484 [11:27<00:39,  1.10s/it]

done with patient sub-01661279
currently working on sub-01309950


 93%|█████████▎| 449/484 [11:28<00:39,  1.13s/it]

done with patient sub-01309950
currently working on sub-02113718


 93%|█████████▎| 450/484 [11:29<00:37,  1.11s/it]

done with patient sub-02113718
currently working on sub-01461078


 93%|█████████▎| 451/484 [11:30<00:37,  1.14s/it]

done with patient sub-01461078
currently working on sub-02124336


 93%|█████████▎| 452/484 [11:31<00:38,  1.19s/it]

done with patient sub-02124336
currently working on sub-01695094


 94%|█████████▎| 453/484 [11:34<00:48,  1.56s/it]

done with patient sub-01695094
currently working on sub-01458719


 94%|█████████▍| 454/484 [11:35<00:43,  1.43s/it]

done with patient sub-01458719
currently working on sub-01204563


 94%|█████████▍| 455/484 [11:37<00:45,  1.56s/it]

done with patient sub-01204563
currently working on sub-02179132


 94%|█████████▍| 456/484 [11:38<00:39,  1.42s/it]

done with patient sub-02179132
currently working on sub-02000864


 94%|█████████▍| 457/484 [11:39<00:37,  1.39s/it]

done with patient sub-02000864
currently working on sub-01983233


 95%|█████████▍| 458/484 [11:40<00:34,  1.32s/it]

done with patient sub-01983233
currently working on sub-02009523


 95%|█████████▍| 459/484 [11:42<00:31,  1.27s/it]

done with patient sub-02009523
currently working on sub-02136965


 95%|█████████▌| 460/484 [11:43<00:29,  1.23s/it]

done with patient sub-02136965
currently working on sub-01243841


 95%|█████████▌| 461/484 [11:44<00:27,  1.20s/it]

done with patient sub-01243841
currently working on sub-01437004


 95%|█████████▌| 462/484 [11:45<00:26,  1.21s/it]

done with patient sub-01437004
currently working on sub-02165732


 96%|█████████▌| 463/484 [11:46<00:24,  1.17s/it]

done with patient sub-02165732
currently working on sub-01370265


 96%|█████████▌| 465/484 [11:48<00:18,  1.03it/s]

done with patient sub-01370265
currently working on sub-01946372


 96%|█████████▋| 466/484 [11:49<00:19,  1.08s/it]

done with patient sub-01946372
currently working on sub-02070903


 96%|█████████▋| 467/484 [11:50<00:18,  1.08s/it]

done with patient sub-02070903
currently working on sub-01754011


 97%|█████████▋| 468/484 [11:52<00:18,  1.17s/it]

done with patient sub-01754011
currently working on sub-02082001


 97%|█████████▋| 469/484 [11:54<00:22,  1.48s/it]

done with patient sub-02082001
currently working on sub-01425882


 97%|█████████▋| 470/484 [11:55<00:19,  1.38s/it]

done with patient sub-01425882
currently working on sub-01906150


 97%|█████████▋| 471/484 [11:56<00:17,  1.34s/it]

done with patient sub-01906150
currently working on sub-02154718


 98%|█████████▊| 472/484 [11:58<00:16,  1.35s/it]

done with patient sub-02154718
currently working on sub-02036251


 98%|█████████▊| 474/484 [11:59<00:09,  1.01it/s]

done with patient sub-02036251
currently working on sub-01797781


 98%|█████████▊| 475/484 [12:00<00:09,  1.01s/it]

done with patient sub-01797781
currently working on sub-01895825


 98%|█████████▊| 476/484 [12:01<00:08,  1.03s/it]

done with patient sub-01895825
currently working on sub-01713570


 99%|█████████▊| 477/484 [12:02<00:07,  1.09s/it]

done with patient sub-01713570
currently working on sub-01213140


 99%|█████████▉| 478/484 [12:03<00:06,  1.09s/it]

done with patient sub-01213140
currently working on sub-01696904


 99%|█████████▉| 479/484 [12:04<00:05,  1.10s/it]

done with patient sub-01696904
currently working on sub-01587295


 99%|█████████▉| 480/484 [12:06<00:04,  1.14s/it]

done with patient sub-01587295
currently working on sub-01494236


 99%|█████████▉| 481/484 [12:08<00:04,  1.58s/it]

done with patient sub-01494236
currently working on sub-01104996


100%|█████████▉| 482/484 [12:09<00:02,  1.43s/it]

done with patient sub-01104996
currently working on sub-01565091


100%|██████████| 484/484 [12:10<00:00,  1.51s/it]

done with patient sub-01565091
471


In [23]:
path_to_image = Path("/Users/LennartPhilipp/Desktop/Uni/Prowiss/Datensatz_RGB/regensburg_test_slices/sub-01134825/sub-01134825_metastasis_105_1_t1.png")

test_image = iio.v3.imread(path_to_image)
print(test_image.shape)

(240, 240)


### Yale Dataset

In [66]:
# output: create folder for each patient and save the slices there

# input mri folder: path to all patient scans, including segmentations
# go to each patient and get all 4 mri scans as well as segmentation

path_to_output = Path("/Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases")
path_to_yale_patients_raw = Path("/Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/Pretreat-MetsToBrain-Masks")
path_to_yale_patients_processed = Path("/Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_dataset_normalized")

yale_patients = [patient for patient in os.listdir(path_to_yale_patients_raw) if os.path.isdir(os.path.join(path_to_yale_patients_raw, patient))]

counter = 0

for patient in tqdm(yale_patients):

    if counter >= 5:
        break

    # go through each patient

    pat_id = patient.split("-")[2]
    
    print(f"currently working on {pat_id}")

    # create new folder for output for patient
    path_to_patient_output = Path(path_to_output) / Path(pat_id)
    os.makedirs(path_to_patient_output, exist_ok=True)

    # IMPORTANT!!!!!
    # adjust path for final run
    path_to_raw_patient_files = Path(path_to_yale_patients_raw) / Path(patient)
    segmentation_file = [file for file in os.listdir(path_to_raw_patient_files) if "seg" in file][0]
    path_to_segmentation = Path(path_to_raw_patient_files) / Path(segmentation_file)

    path_to_mri_images = Path(path_to_yale_patients_processed) / Path(patient)
    mri_images = [file for file in os.listdir(path_to_mri_images) if "normalized" in file]

    if len(mri_images) != 4:
        print("********************************")
        print(f"patient {patient} not complete")
        continue

    for mri_image in mri_images:
        # go through each mri image for the patient

        mri_sequence = mri_image.split("-")[4].split(".")[0]

        path_to_mri = Path(path_to_mri_images) / Path(mri_image)
        process_nifty_mask(
            mask_path = path_to_segmentation,
            mri_path = path_to_mri,
            output_dir = path_to_patient_output,
            patient_id = pat_id,
            mri_sequence = mri_sequence,
            save_mask_image = True,
            save_cut_out = True,
            dataset = "yale"
        )
        #process_nifty_mask(path_to_segmentation, path_to_mri, path_to_patient_output, patient_id = pat_id, mri_sequence)
    
    counter += 1

    print(f"done with patient {patient}")
    

  0%|          | 0/200 [00:00<?, ?it/s]

currently working on 00086
[0. 2. 3.]
[0. 2. 3.]
Saved largest slice for metastasis (slice 48) with area 33 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00086/00086_metastasis_48_1_t1c.nii.gz_cutout.png
Saved largest slice for metastasis (slice 50) with area 29 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00086/00086_metastasis_50_2_t1c.nii.gz_cutout.png
Saved largest slice for metastasis (slice 39) with area 43 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00086/00086_metastasis_39_3_t1c.nii.gz_cutout.png
[0. 2. 3.]
[0. 2. 3.]
Saved largest slice for metastasis (slice 48) with area 33 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00086/00086_metastasis_48_1_t2w.nii.gz_cutout.png
Saved largest slice for metastasis (slice 50) with area 29 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00086/00086_metastasis_50_2_t2w.nii.gz_cutout.png

  0%|          | 1/200 [00:02<08:29,  2.56s/it]

Saved largest slice for metastasis (slice 39) with area 43 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00086/00086_metastasis_39_3_t2f.nii.gz_cutout.png
done with patient BraTS-MET-00086-000
currently working on 00284
[0. 1. 2. 3.]
[0. 1. 2.]
Saved largest slice for metastasis (slice 60) with area 390 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00284/00284_metastasis_60_1_t2f.nii.gz_cutout.png
[0. 1. 2. 3.]
[0. 1. 2.]
Saved largest slice for metastasis (slice 60) with area 390 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00284/00284_metastasis_60_1_t1n.nii.gz_cutout.png
[0. 1. 2. 3.]
[0. 1. 2.]
Saved largest slice for metastasis (slice 60) with area 390 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00284/00284_metastasis_60_1_t2w.nii.gz_cutout.png
[0. 1. 2. 3.]
[0. 1. 2.]


  1%|          | 2/200 [00:03<06:13,  1.89s/it]

Saved largest slice for metastasis (slice 60) with area 390 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00284/00284_metastasis_60_1_t1c.nii.gz_cutout.png
done with patient BraTS-MET-00284-000
currently working on 00290
[0. 1. 2. 3.]
[0. 1. 2.]
Saved largest slice for metastasis (slice 71) with area 715 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00290/00290_metastasis_71_1_t1n.nii.gz_cutout.png
[0. 1. 2. 3.]
[0. 1. 2.]
Saved largest slice for metastasis (slice 71) with area 715 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00290/00290_metastasis_71_1_t2f.nii.gz_cutout.png
[0. 1. 2. 3.]
[0. 1. 2.]
Saved largest slice for metastasis (slice 71) with area 715 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00290/00290_metastasis_71_1_t2w.nii.gz_cutout.png
[0. 1. 2. 3.]
[0. 1. 2.]


  2%|▏         | 3/200 [00:05<05:28,  1.67s/it]

Saved largest slice for metastasis (slice 71) with area 715 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00290/00290_metastasis_71_1_t1c.nii.gz_cutout.png
done with patient BraTS-MET-00290-000
currently working on 00247
[0. 1. 2. 3.]
[0. 1. 2.]
Saved largest slice for metastasis (slice 31) with area 79 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00247/00247_metastasis_31_1_t1c.nii.gz_cutout.png
[0. 1. 2. 3.]
[0. 1. 2.]
Saved largest slice for metastasis (slice 31) with area 79 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00247/00247_metastasis_31_1_t2w.nii.gz_cutout.png
[0. 1. 2. 3.]
[0. 1. 2.]
Saved largest slice for metastasis (slice 31) with area 79 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00247/00247_metastasis_31_1_t1n.nii.gz_cutout.png
[0. 1. 2. 3.]
[0. 1. 2.]


  2%|▏         | 4/200 [00:06<05:03,  1.55s/it]

Saved largest slice for metastasis (slice 31) with area 79 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00247/00247_metastasis_31_1_t2f.nii.gz_cutout.png
done with patient BraTS-MET-00247-000
currently working on 00253
[0. 1. 2. 3.]
[0. 1. 2.]
Saved largest slice for metastasis (slice 63) with area 76 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00253/00253_metastasis_63_1_t1c.nii.gz_cutout.png
Saved largest slice for metastasis (slice 103) with area 117 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00253/00253_metastasis_103_2_t1c.nii.gz_cutout.png
Saved largest slice for metastasis (slice 73) with area 366 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00253/00253_metastasis_73_3_t1c.nii.gz_cutout.png
Saved largest slice for metastasis (slice 116) with area 53 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00253/00253_metastasis_11

  2%|▎         | 5/200 [00:10<06:33,  2.02s/it]

Saved largest slice for metastasis (slice 73) with area 366 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00253/00253_metastasis_73_3_t1n.nii.gz_cutout.png
Saved largest slice for metastasis (slice 116) with area 53 to /Users/LennartPhilipp/Desktop/Uni/Prowiss/CIA metstobrain/yale_metastases/00253/00253_metastasis_116_4_t1n.nii.gz_cutout.png
done with patient BraTS-MET-00253-000
